
import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const CONTENT_DIR = path.join(__dirname, '../content/articles');
const OUTPUT_DIR = path.join(__dirname, '../src/data');
const CATALOG_FILE = path.join(OUTPUT_DIR, 'catalog.json');
const MAPPING_FILE = path.join(OUTPUT_DIR, 'mapping.ts');

if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

console.log('🏗️  Generating Content Catalog...');

const files = fs.readdirSync(CONTENT_DIR).filter(file => file.endsWith('.md'));
const catalog = [];
const mappingLines = [];

mappingLines.push('// Generated by scripts/generate-catalog.js');
mappingLines.push('// Do not edit manually');
mappingLines.push('');
mappingLines.push('export const ARTICLE_CONTENT_MAP: Record<string, () => Promise<any>> = {');

files.forEach(file => {
    const filePath = path.join(CONTENT_DIR, file);
    const fileContent = fs.readFileSync(filePath, 'utf-8');
    const { data } = matter(fileContent);

    if (!data.id) {
        console.warn(`⚠️  Skipping ${file}: Missing 'id' in frontmatter.`);
        return;
    }

    // Add filename to data for reference
    const item = {
        ...data,
        fileName: file,
        // Extract text content for search (filtering out frontmatter)
        searchText: matter(fileContent).content.replace(/[#*`]/g, '') // Simple markdown strip
    };

    catalog.push(item);

    // Create mapping entry for lazy loading
    // Using absolute relative path from src/data/mapping.ts to content/articles/...
    mappingLines.push(`  "${data.id}": () => import('../../content/articles/${file}?raw'),`);
});

mappingLines.push('};');

// Write Catalog JSON
fs.writeFileSync(CATALOG_FILE, JSON.stringify(catalog, null, 2));
console.log(`✅ Catalog generated with ${catalog.length} items at ${CATALOG_FILE}`);

// Write Mapping TS
fs.writeFileSync(MAPPING_FILE, mappingLines.join('\n'));
console.log(`✅ Lazy load mapping generated at ${MAPPING_FILE}`);
