// Generated by scripts/generate-catalog.js
// Do not edit manually

export const ARTICLE_CONTENT_MAP: Record<string, () => Promise<any>> = {
  "aposentadoria-especial": () => import('../../content/articles/aposentadoria-especial.md?raw'),
  "aposentadoria-invalidez": () => import('../../content/articles/aposentadoria-invalidez.md?raw'),
  "cat": () => import('../../content/articles/cat.md?raw'),
  "ecac-guia": () => import('../../content/articles/ecac-guia.md?raw'),
  "esocial-sst": () => import('../../content/articles/esocial-sst.md?raw'),
  "intro-sst": () => import('../../content/articles/intro-sst.md?raw'),
  "ltcat": () => import('../../content/articles/ltcat.md?raw'),
  "pcmso": () => import('../../content/articles/pcmso.md?raw'),
  "pgr": () => import('../../content/articles/pgr.md?raw'),
  "pgrtr": () => import('../../content/articles/pgrtr.md?raw'),
  "ppp": () => import('../../content/articles/ppp.md?raw'),
};