// Generated by scripts/generate-catalog.js
// Do not edit manually

export const ARTICLE_CONTENT_MAP: Record<string, () => Promise<{ default: { content: string } }>> = {
  "aposentadoria-especial": () => import('./chunks/aposentadoria-especial.json'),
  "aposentadoria-invalidez": () => import('./chunks/aposentadoria-invalidez.json'),
  "cat": () => import('./chunks/cat.json'),
  "ecac-guia": () => import('./chunks/ecac-guia.json'),
  "esocial-sst": () => import('./chunks/esocial-sst.json'),
  "intro-sst": () => import('./chunks/intro-sst.json'),
  "ltcat": () => import('./chunks/ltcat.json'),
  "pcmso": () => import('./chunks/pcmso.json'),
  "pgr": () => import('./chunks/pgr.json'),
  "pgrtr": () => import('./chunks/pgrtr.json'),
  "ppp": () => import('./chunks/ppp.json'),
};